language: node_js

node_js:
  - '10'

dist: trusty

install:
  - npm ci 

# deploy:
#   provider: npm
#   edge: true
#   email: dannydainton@gmail.com
#   api_key: $NPM_TOKEN
#   on:
#     branch: master
